Add container label in hc.nf
Loos like a container label is missing in hc.nf, process HC_SUPPORTED. Different tools available in the image are called, but no container label is present. In my case I get:

RuntimeError: TransDecoder coordinate transformation failed.: [Errno 2] No such file or directory: 'cdna_alignment_orf_to_genome_orf.pl'

Adding the container label fixes this issue for me.